version: "3.8"

services:
  vite-service:
    container_name: my-github-pages-container

    image: takanarishimbo/my-github-pages:v1.0.0

    ports:
      - "${SERVER_PORT}:8000"

    command: npm run vite-preview
    # command: npm run static-preview

    restart: always
